
const data = [
  {
    id:1,
    img: "https://www.wallpapershop.co.uk/images/graham-and-…at-panel-wallpaper-natural-p4136-28558_medium.jpg",
    title: "Wooden Slat Panel Wallpaper Natural",
    newPrice: "£14.99",
    company: "Honor",
    color: "wood",
    category: "sneakers",
  },
  {
    id:2,
    img: "	https://www.wallpapershop.co.uk/images/belgravia-decor-panacea-wood-wallpaper-p4899-32748_medium.jpg",
    title: "Panacea Wood Wallpaper",
    newPrice: "£12.95",
    company: "Diamond",
    color: "wood",
    category: "sneakers",
  },

  {
    id:3,
    img: "	https://www.wallpapershop.co.uk/images/belgravia-d…alian-thick-vinyl-wallpaper-p3038-25023_thumb.jpg",
    title: "Amara Wood Panel Satin Finish Italian Thick Vinyl Wallpaper",
    newPrice: "£13.95",
    company: "Diamond",
    color: "white",
    category: "sneakers",
  },
  {
    id:4,
    img: "	https://www.wallpapershop.co.uk/images/debona-heri…ood-effect-panel-wallpaper-p2855-22153_medium.jpg",
    title: "Modern Wood Panel Wallpaper",
    newPrice: "£13.95",
    company: "Carat",
    color: "blue",
    category: "sneakers",
  },
  {
    id:5,
    img: "	https://www.wallpapershop.co.uk/images/belgravia-decor-oliana-panel-wallpaper-p3176-23931_medium.jpg",
    title: "Oliana Panel Wallpaper",
    newPrice: "£11.95",
    company: "Carat",
    color: "red",
    category: "flats",
  },
  {
    id:6,
    img: "	https://www.wallpapershop.co.uk/images/y%C3%B6l-wo…panel-wallpaper-white-grey-p2737-21734_medium.jpg",
    title: "Wood Panel Wallpaper White",
    newPrice: "£13.95",
    company: "Diamond",
    color: "white",
    category: "flats",
  },

  {
    id:7,
    img: "https://www.wallpapershop.co.uk/images/belgravia-d…lian-thick-vinyl-wallpaper-p3038-25025_medium.jpg",
    title: "Amara Wood Panel Satin Finish Italian Thick Vinyl Wallpaper",
    newPrice: "£13.95",
    company: "Diamond",
    color: "black",
    category: "flats",
  },

  {
    id:8,
    img: "https://www.wallpapershop.co.uk/images/belgravia-decor-oliana-panel-wallpaper-p3176-23935_medium.jpg",
    title: "Oliana Panel Wallpaper",
    newPrice: "£13.95",
    company: "Honor",
    color: "green",
    category: "sneakers",
  },

  {
    id:9,
    img: "	https://www.wallpapershop.co.uk/images/holden-deco…odern-wood-panel-wallpaper-p3294-24302_medium.jpg",
    title: "Modern Wood Panel Wallpaper",
    newPrice: "£13.95",
    company: "Diamond",
    color: "blue",
    category: "sneakers",
  },

  {
    id:10,
    img: "https://www.wallpapershop.co.uk/images/belgravia-d…rra-panel-effect-wallpaper-p3795-26900_medium.jpg",
    title: "Azzurra Panel Effect Wallpaper",
    newPrice: "£11.95",
    company: "Honor",
    color: "white",
    category: "sneakers",
  },
  {
    id:11,
    img: "	https://www.wallpapershop.co.uk/images/belgravia-d…lian-thick-vinyl-wallpaper-p3038-24989_medium.jpg",
    title: "Amara Wood Panel Satin Finish Italian Thick Vinyl Wallpaper",
    newPrice: "£24.95",
    company: "Oreintal",
    color: "white",
    category: "sneakers",
  },
  {
    id:12,
    img: "	https://www.wallpapershop.co.uk/images/debona-harrow-wood-effect-wallpaper-p3108-34329_thumb.jpg",
    title: "Harrow Wood Effect Wallpaper",
    newPrice: "£11.95",
    company: "Oreintal",
    color: "blue",
    category: "sneakers",
  },
  {
    id:13,
    img: "	https://www.wallpapershop.co.uk/images/fine-decor-carved-panel-wallpaper-p5210-35901_thumb.jpg",
    title: "Carved Panel Wallpaper",
    newPrice: " £6.95",
    company: "Oreintal",
    color: "green",
    category: "sneakers",
  },
  {
    id:14,
    img: "	https://www.wallpapershop.co.uk/images/grandeco-pa…enny-rococo-panel-wallpaper-p5214-35992_thumb.jpg",
    title: "Paul Moneypenny Rococo Panel Wallpaper",
    newPrice: "£12.95",
    company: "Honor",
    color: "white",
    category: "sneakers",
  },

  {
    id:15,
    img: "https://www.wallpapershop.co.uk/images/grandeco-pa…enny-rococo-panel-wallpaper-p5214-35997_thumb.jpg",
    title: "Paul Moneypenny Rococo Panel Wallpaper",
    newPrice: "£24.95",
    company: "Oreintal",
    color: "blue",
    category: "sneakers",
  },
  {
    id:16,
    img: "https://www.wallpapershop.co.uk/images/arthouse-fl…-planks-wallpaper-navy-blue-p5313-37016_thumb.jpg",
    title: "Flat Wooden Planks Wallpaper Navy Blue",
    newPrice: "£8.95",
    company: "Honor",
    color: "blue",
    category: "flats",
  },
  {
    id:17,
    img: "https://www.wallpapershop.co.uk/images/arthouse-diamond-floral-wallpaper-glitter-p2-8827_thumb.jpg",
    title: "Diamond Floral Wallpaper Glitter",
    newPrice: "£11.95",
    company: "Oreintal",
    color: "white",
    category: "sandals",
  },
  {
    id:18,
    img: "https://www.wallpapershop.co.uk/images/arthouse-di…d-galaxy-glitter-star-wallpaper-p5-8922_thumb.jpg",
    title: "Diamond Galaxy Glitter Star Wallpaper",
    newPrice: "£12.95",
    company: "Oreintal",
    color: "red",
    category: "sandals",
  },
  {
    id:19,
    img: "https://www.wallpapershop.co.uk/images/arthouse-ur…realistic-brick-wall-wallpaper-p71-9753_thumb.jpg",
    title: "Urban Realistic Brick Wall Wallpaper",
    newPrice: "£24.95",
    company: "Honor",
    color: "red",
    category: "sandals",
  },
  {
    id:20,
    img: "https://www.wallpapershop.co.uk/images/debona-vertical-marble-wallpaper-p5320-37107_thumb.jpg",
    title: "Vertical Marble Wallpaper",
    newPrice: "£24.95",
    company: "Carat",
    color: "white",
    category: "heels",
  },
  {
    id:21,
    img: "	https://www.wallpapershop.co.uk/images/grandeco-te…ical-art-concrete-wallpaper-p4958-33159_thumb.jpg",
    title: "Textured Vertical Art Concrete Wallpaper",
    newPrice: " £13.95",
    company: "Carat",
    color: "white",
    category: "heels",
  },
  {
    id:22,
    img: "	https://www.wallpapershop.co.uk/images/crown-crane-flying-bird-wallpaper-p4213-28849_thumb.jpg",
    title: "Crane Flying Bird Wallpaper",
    newPrice: " £11.95",
    company: "Carat",
    color: "red",
    category: "heels",
  },
  {
    id:23,
    img: "	https://www.wallpapershop.co.uk/images/belgravia-decor-oliana-panel-wallpaper-p3176-24981_thumb.jpg",
    title: "Oliana Panel Wallpaper",
    newPrice: "£24.95",
    company: "Oreintal",
    color: "green",
    category: "sneakers",
  },

  {
    id:24,
    img: "https://www.wallpapershop.co.uk/images/belgravia-d…-flower-wallpaper-black-red-p2297-19391_thumb.jpg",
    title: "Angelica Flower Wallpaper Black & Red",
    newPrice: "£13.95",
    company: "Carat",
    color: "red",
    category: "heels",
  },
  {
    id:25,
    img: "https://www.wallpapershop.co.uk/images/muriva-rosalee-floral-wallpaper-p668-1030_thumb.jpg",
    title: "Rosalee Floral Wallpaper",
    newPrice: "£13.95",
    company: "Oreintal",
    color: "red",
    category: "heels",
  },
  {
    id:26,
    img: "	https://www.wallpapershop.co.uk/images/muriva-linen-textured-plain-wallpaper-p2617-24618_thumb.jpg",
    title: "Linen Textured Plain Wallpaper",
    newPrice: "£11.95",
    company: "Carat",
    color: "black",
    category: "heels",
  },
  {
    id:27,
    img: "https://www.wallpapershop.co.uk/images/versace-ver…l-greek-key-stripe-wallpaper-p899-10428_thumb.jpg",
    title: "Vertical Greek Key Stripe Wallpaper",
    newPrice: "£12.95",
    company: "Carat",
    color: "black",
    category: "heels",
  },
  {
    id:28,
    img: "	https://www.wallpapershop.co.uk/images/muriva-blin…ngster-wallpaper-gold-black-p1672-19468_thumb.jpg",
    title: "Bling Guns Gangster Wallpaper Gold Black",
    newPrice: "£24.95",
    company: "Diamond",
    color: "black",
    category: "flats",
  },
  {
    id:29,
    img: "	https://www.wallpapershop.co.uk/images/holden-deco…-tropical-art-deco-wallpaper-p1202-6348_thumb.jpg",
    title: "Congo Tropical Art Deco Wallpaper",
    newPrice: "£12.95",
    company: "Carat",
    color: "green",
    category: "flats",
  },
  {
    id:30,
    img: "https://www.wallpapershop.co.uk/images/arthouse-tr…-leaves-leaf-wallpaper-green-p185-10104_thumb.jpg",
    title: "Tropical Palm Leaves Leaf Wallpaper Green",
    newPrice: "£13.95",
    company: "Diamond",
    color: "green",
    category: "flats",
  },
];

export default data;
